mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.contrib import admin
from django.urls import path
from polls import views

urlpatterns = [
    path('', views.index),
    path('<int:id>', views.detail, name='detail'),
    path('vote/', views.vote, name='vote'),
    path('<int:number>/data/<str:email>', views.data, name='user_name'),
    path('input', views.input, name='add'),
    path('add_question/', views.add_question, name='text'),
    path('result/<int:id>', views.result, name='result'),
]

polls/models.py
from django.db import models

# Create your models here.
# ctrl + alt + l 눌러주면 코드정렬!!
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text + ' // ' + str(self.votes)

polls/views.py
from django.http import HttpResponse
from django.shortcuts import render
from polls.models import Question, Choice
from django.utils import timezone

def result(request, id) :  # 투표의 결과를 보여줌
    question = Question.objects.get(pk=id)
    return render(request, 'polls/result.html', {'question' : question})

def add_question(request) :  # 질문을 추가하고난 다음 페이지
    text = request.POST['text']
    q = Question(question_text=text, pub_date=timezone.now())
    q.save()
    return render(request, 'polls/add_question.html', {})

def input(request) :  # 질문을 추가 할 페이지
    return render(request, 'polls/input.html', {})

def data(request, email, number) :  # data를 확인 할 페이지
    # http://localhost:8000/polls/data?user_name=kim
    value = request.GET['user_name']
    return HttpResponse(value + email + str(number))

def vote(request) :  # 투표 할 페이지
    choice = request.POST['choice']
    print('@^_^@', choice) # 서버에 client의 결과를 보여주게끔
    c = Choice.objects.get(pk=choice)
    c.votes += 1
    c.save()

    return render(request, 'polls/vote.html', {})

def detail(request, id) :  # DB에 입력되어 있는 질문과 답변의 보기를 보여주는 페이지
    question = Question.objects.get(id=id)
    return render(request, 'polls/detail.html', {'item' : question})

def index(request) :  # 질문 리스트들을 출력해줄 페이지(a태그 이용 링크걸기)
    # return HttpResponse('index!!!') 단순히 화면출력을 위한 것
    list = Question.objects.all()
    return render(request, 'polls/index.html', {'question' : list})

polls/templates/polls/add_question.html
<h1> 입력완료!! </h1>

polls/templates/polls/detail.html
{{ item.question_text }} <br>
{{ item.pub_date }} <br><br>

{{ item.choice_set.all }} <br><br>

<form action="vote/" method="post">
{% for c in item.choice_set.all %}
    <input type="radio" name="choice" value="{{c.id}}">
    {{ c.choice_text }}
{% endfor %}
    {% csrf_token %} <!-- 보안조치 -->
    <input type="submit" value="투표">
</form>

polls/templates/polls/index.html
<ul>
{% for q in question %}
    <li>
        <!-- 상대경로 = 현재경로 + 입력된 경로-->
        <!--<a href="{{ q.id }}">-->
        <a href="{% url 'detail' q.id %}">
        {{q.question_text}}
        </a>
    </li>
{% endfor %}
</ul>

polls/templates/polls/input.html
<form action="add_question/" method="post">
    <input type="text" name="text">

    {% csrf_token %}
    <input type="submit" value="추가">
</form>

polls/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>result</title>
</head>
<body>
    질문 : {{ question.question_text }}<br><br>

    <!--{{ question.choice_set.all }}<br><br> &lt;!&ndash; 이렇게 쓰면 모든 보기가 출력됨(ORM이라 가능한 것 choice_set) &ndash;&gt;-->

    [ 투표결과 ] <br>
    {% for choice in question.choice_set.all %}
        {{ choice.choice_text }} --> {{ choice.votes }}<br>
    {% endfor %}

</body>
</html>

polls/templates/polls/vote.html
<h1> 투표완료 </h1>